# Generated by Django 3.2.8 on 2021-10-20 06:33

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя партнёра')),
                ('image', models.ImageField(upload_to=partners.models.Partner.upload_to, verbose_name='Фотография партнёра')),
                ('url', models.URLField(max_length=255, null=True, verbose_name='Ссылка на партнёра')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
