# Generated by Django 3.2.8 on 2021-10-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на источник')),
            ],
            options={
                'verbose_name': 'Пресса',
                'verbose_name_plural': 'Пресса',
            },
        ),
    ]
